### ISSUE TITLE
Issue with running Jupyterlab with extension using docker-compose 

### ISSUE THREAD

**Issue by vemonet** [fair-workflows/FAIRWorkflowsExtension#12]
Trying to start Jupyterlab with FAIRWorkflowsExtension using `docker-compose` fails 

From this github repo:

```
docker-compose up
```

Raise issue:

```
  File "/app/FAIRWorkflowsExtension/__init__.py", line 2, in <module>
    from .nanopub_handlers import nanopub_search_handler, nanopub_step_handler
  File "/app/FAIRWorkflowsExtension/nanopub_handlers.py", line 10, in <module>
    import fairworkflows
  File "/opt/conda/lib/python3.7/site-packages/fairworkflows/__init__.py", line 5, in <module>
    from .ro_crate import ROCrate
  File "/opt/conda/lib/python3.7/site-packages/fairworkflows/ro_crate.py", line 7, in <module>
    from . import cwl
  File "/opt/conda/lib/python3.7/site-packages/fairworkflows/cwl.py", line 6, in <module>
    from toil.cwl import cwltoil
  File "/opt/conda/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 78, in <module>
    from cwltool.utils import aslist, convert_pathsep_to_unix, get_listing, normalizeFilesDirs, CWLObjectType
ImportError: cannot import name 'get_listing' from 'cwltool.utils' (/opt/conda/lib/python3.7/site-packages/cwltool/utils.py)
ERROR: Service 'jupyterlab' failed to build: The command '/bin/sh -c jupyter-serverextension enable --py FAIRWorkflowsExtension' returned a non-zero code: 1
```

> Exactly the same issue happens with NanopubsJL

The issue seems to be related to https://github.com/fair-workflows/FAIRWorkbench/blob/master/fairworkflows/cwl.py#L6 

CWL toil try to `import get_listing` from `cwltool.utils`, but cannot find it. It seems that get_listing has been introduced in cwltool 3.0, and the FAIRWorkbench requires cwltool 2.0

**Comment by raar1** [comment]
Hi Vincent! Thanks a lot and sorry about the issue (you're right, it was affecting NanopubJL etc as well). Due to some design choices made last week we're actually now taking out the cwl component (at least, the execution stuff) and the workflowhub related elements (for now). It will likely be back, in one form or another, but currently we're trying to focus the design of the core library. I've removed the offending code completely, otherwise I would of course have merged your PR (thanks again).

If you have the time, would you be able to try running the extension(s) again just to check that they are now building/running for you as well?

**Comment by vemonet** [comment]
Yes, it is working fine now! Thanks
